#ifndef MICRO_ROS_MIRS24
#define MICRO_ROS_MIRS24

#define MICRO_ROS_MIRS24_DISTRO humble
#define MICRO_ROS_MIRS24_VERSION_MAJOR 3
#define MICRO_ROS_MIRS24_VERSION_MINOR 0
#define MICRO_ROS_MIRS24_VERSION_PATCH 0
#define MICRO_ROS_MIRS24_VERSION_BUILD 0
#define IS_MICRO_ROS_MIRS24_MIN_VERSION(major,minor,patch,build) ( \
  (MICRO_ROS_MIRS24_VERSION_MAJOR >= major) && \
  (MICRO_ROS_MIRS24_VERSION_MINOR >= minor) && \
  (MICRO_ROS_MIRS24_VERSION_PATCH >= patch) && \
  (MICRO_ROS_MIRS24_VERSION_BUILD >= build))

#include <micro_ros_arduino.h>

#endif